// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDguFjLLde-dbrKRDMCBIZqx5CuMB6hh88',
    appId: '1:585194788716:web:5fdd730758837ae2d28549',
    messagingSenderId: '585194788716',
    projectId: 'fluttergram-10a7b',
    authDomain: 'fluttergram-10a7b.firebaseapp.com',
    storageBucket: 'fluttergram-10a7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASp21Z_6QlKVOHi1qBhdQnmoDfTHxTzgg',
    appId: '1:585194788716:android:7b5ba07f728fa4fbd28549',
    messagingSenderId: '585194788716',
    projectId: 'fluttergram-10a7b',
    storageBucket: 'fluttergram-10a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm558Cn3iROw023WBR05DhMs-ws88xiWA',
    appId: '1:585194788716:ios:e04c8944817c483ad28549',
    messagingSenderId: '585194788716',
    projectId: 'fluttergram-10a7b',
    storageBucket: 'fluttergram-10a7b.appspot.com',
    iosClientId: '585194788716-j937b0db94qnmtd0v5an7c2lfomrc84u.apps.googleusercontent.com',
    iosBundleId: 'com.hyunminko.instagram',
  );
}
